### ISSUE TITLE
is this a task for a junior or middle position? 

### ISSUE THREAD

**Issue by sk10az** [andrsj/go-rabbit-image#1]
is this a task for a junior or middle position?

**Comment by andrsj** [comment]
@sk10az , it's a task for Strong Junior Golang developer. The main idea it's a displaying the skills of understanding clean architecture in Golang development. So the functionality is easy, but you need separate the business logic and real implementation)

**Comment by sk10az** [comment]
Thanks!)

**Comment by andrsj** [comment]
@sk10az if you want, you can see my implementation of the task and the actual feedback. The project can be improved a lot but it isn't important for this task)
